<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-3M92PDJ" failures="1" tests="6" name="Test1" time="14.296" errors="0" timestamp="2023-10-10T09:16:30 IST">
  <testcase classname="testng2.Testngwithdataprovider" name="navigateurl" time="2.131"/>
  <testcase classname="testng2.Testngwithdataprovider" name="pageinfo" time="0.017"/>
  <testcase classname="testng2.Testngwithdataprovider" name="searchproduct" time="4.484"/>
  <testcase classname="testng2.Testngwithdataprovider" name="searchproduct" time="3.106"/>
  <testcase classname="testng2.Testngwithdataprovider" name="searchproduct" time="2.123"/>
  <testcase classname="testng2.Testngwithdataprovider" name="searchproductandcat" time="0.0">
    <failure type="java.lang.RuntimeException" message="java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2">
      <![CDATA[java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2
at testng2.Testngwithdataprovider.setpdornameandprodcategory(Testngwithdataprovider.java:45)
... 25 more
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- searchproductandcat -->
</testsuite> <!-- Test1 -->
